In [1]:
%cd ..

/home/boat/proxyISP/pytorch-superpoint

/home/boat/miniconda3/envs/proxyopt/lib/python3.12/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [2]:
import sys
import yaml
import torch
import pickle
import cv2
import rawpy
import numpy as np
import matplotlib.pyplot as plt
sys.path.insert(0, "../ProxyOpt/")
sys.path.insert(0, "../fast-openISP/")
sys.path.insert(0, "../ProxyOpt/pytorch-msssim/")
from models.model_wrap import SuperPointFrontend_torch

# config_path = "/home/boat/proxyISP/pytorch-superpoint/configs/superpoint_coco_train_heatmap_proxyopt.yaml"
config_path = "/home/boat/proxyISP/pytorch-superpoint/configs/magicpoint_coco_export.yaml"
with open(config_path, "r") as f:
    config = yaml.safe_load(f)

config.setdefault("model", {}).setdefault("subpixel", {})["enable"] = False

path = config["pretrained"]
assert "170000" in path
nms_dist = 4
nn_thresh = 0.7
conf_thresh = config["model"]["detection_threshold"]
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

magicpoint_gpu_id = "1" if torch.cuda.device_count() > 1 else "0"
magicpoint_device = torch.device(f"cuda:{magicpoint_gpu_id}" if torch.cuda.is_available() else "cpu")
fe = SuperPointFrontend_torch(
        config=config,
        weights_path=path,
        nms_dist=nms_dist,
        conf_thresh=conf_thresh,
        nn_thresh=nn_thresh,
        cuda=False,
        device=magicpoint_device,
)

from ISP_tools.ProxyISPDataset import ProxyISPDataset, EXPERIMENT_OUTPUT_PATH

train_config_path = "/home/boat/proxyISP/ProxyOpt/train_configs/v16.2-chroma-HumanTunedInitialHype.yaml"

with open(train_config_path, "r") as f:
        yaml_dict = yaml.safe_load(f)

config = yaml_dict["config"]
openisp_config = yaml_dict["openisp_config"]
hyp_setting = yaml_dict["hyp_setting"]
additional_conf = {
    "proxyopt_base_path" : "/home/boat/proxyISP/ProxyOpt"
}
dataset = ProxyISPDataset(config, openisp_config, hyp_setting, additional_conf)

model:  SuperPointNet_gauss2

/home/boat/proxyISP/pytorch-superpoint/models/model_wrap.py:100: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(weights_path,
[01-19 22:21:44] ProxyISPDataset.py INFO - Initializing ProxyISPDataset Dataset...
INFO:ISP_tools.ProxyISPDataset:Initializing ProxyISPDataset Dataset...
[01-19 22:21:44] ProxyISPDataset.py INFO - total raw images: 1073
INFO:ISP_tools.ProxyISPDataset:total raw images: 1073

self.config {'experiment_name': 'actual_proxy_v16.2-chroma', 'model_choice': 'proxyopt_unet', 'loss_choice': 'msssim', 'optimizer_choice': 'adam', 'input_type': 'stacked', 'output_domain': 'rgb', 'raw_path': '/mnt/ssd2tb/boat/thesis/s21fe_dataset', 'crop_mode': 'random', 'num_hyperp_to_sample': 50000, 'num_data_to_sample': False, 'img_size': 'dynamic', 'lr': 0.001, 'batch_size': 1, 'epoch': 200000, 'save_iter': 1000, 'save_only_latest': False, 'eval_iter': 10000, 'save_image_iter': 1000, 'lr_scheduler_iter': 13000, 'train_val_ratio': 0.85, 'gradient_accum_step': 1, 'memory_replay_prob': 0, 'memory_replay_buffer': 50, 'device': 'cuda', 'seed': 8888}

[01-19 22:21:45] ProxyISPDataset.py INFO - hyperp length: 50000
INFO:ISP_tools.ProxyISPDataset:hyperp length: 50000
[01-19 22:21:45] ProxyISPDataset.py INFO - num_hyperp x num_image: 53650000
INFO:ISP_tools.ProxyISPDataset:num_hyperp x num_image: 53650000
[01-19 22:21:53] ProxyISPDataset.py INFO - total dataset length: 53650000
INFO:ISP_tools.ProxyISPDataset:total dataset length: 53650000

In [3]:
import os
import glob
import pickle
import rawpy
import numpy as np
import pandas as pd
import cv2
import torch
from tqdm import tqdm


# =========================
# Helper functions
# =========================

def keypoint_entropy_and_coverage(kps_xy, H, W, grid=(4, 4), eps=1e-12):
    """
    kps_xy: (N, 2) array of (x, y)
    H, W: image height and width
    Returns:
        entropy (normalized to [0,1])
        coverage ratio [0,1]
    """
    gx, gy = grid
    hist = np.zeros((gy, gx), dtype=np.float32)

    for x, y in kps_xy:
        ix = min(int(x / W * gx), gx - 1)
        iy = min(int(y / H * gy), gy - 1)
        hist[iy, ix] += 1

    # coverage
    coverage = (hist > 0).mean()

    # entropy
    p = hist.flatten()
    p = p / (p.sum() + eps)
    entropy = -np.sum(p * np.log(p + eps)) / np.log(len(p))

    return entropy, coverage


# =========================
# 1. USER CONFIG
# =========================

hype_paths = [
    "/home/boat/proxyISP/ProxyOpt/v16.2-chroma-HumanTunedInitialHype_replicate-s21fe_sunlit_lr0.0005_schedulerPlateauTo0.00001_bs1_ga8_adjust_defaultcolorhuesat/checkpoints/checkpoint_120000.pkl",
    "/home/boat/proxyISP/pytorch-superpoint/logs/PRETRAINED_SAMEMODELHOMOADAPT_AGGRESSIVEHOMOADAPT_CFANORMALIZE_XHOMOWARP_DETERMHOMOADAPT_train_v16.2-chroma-HumanTunedInitialHype_sunlit_lr0.005_bothLoss_initialHypeHomoAdaptOnly_gradac187/proxyopt_checkpoints/checkpoint_78500.pkl",
]

SEQ_PREFIX = "sl_*"

hpatches_root = "/mnt/ssd2tb/boat/thesis/s21fe_hpatches_v4"

RAW_CROP = (slice(540, 2460), slice(1040, 2960))
SP_SIZE = np.array([240, 320])  # (H, W)


# =========================
# 2. LOAD ALL HYPERPARAMS
# =========================

hypes = []
hype_names = []

for p in hype_paths:
    with open(p, "rb") as f:
        hyp = pickle.load(f)["proxy_hype"]
        hyp = dataset.denormalize_hyp(hyp)
    hypes.append(hyp)
    hype_names.append(os.path.basename(p))

# prepend original
hypes.insert(0, None)
hype_names.insert(0, "original")


# =========================
# 3. GLOB ALL DNG FILES
# =========================

dng_files = sorted(
    glob.glob(os.path.join(hpatches_root, SEQ_PREFIX, "*.dng"))
)

print(f"Found {len(dng_files)} DNG files")


# =========================
# 4. MAIN PIPELINE
# =========================

results = []

for idx, raw_path in enumerate(tqdm(dng_files, desc="Processing RAW images")):

    # ---- read raw ----
    with rawpy.imread(raw_path) as raw:
        bayer = raw.raw_image.copy()

    bayer = bayer[RAW_CROP]

    row = {
        "count": idx,
        "image": os.path.relpath(raw_path, hpatches_root),
    }

    for hyp, hyp_name in zip(hypes, hype_names):

        # ---- ISP processing ----
        if hyp is None:
            img = dataset.process_raw(bayer)
        else:
            img = dataset.process_raw(bayer, hyp)

        # ---- SuperPoint preprocessing ----
        gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        gray = cv2.resize(
            gray,
            (SP_SIZE[1], SP_SIZE[0]),
            interpolation=cv2.INTER_AREA
        )
        gray = gray.astype(np.float32) / 255.0
        gray = torch.from_numpy(gray)[None, None, :, :]  # [1,1,H,W]

        # ---- SuperPoint inference ----
        with torch.no_grad():
            pts, pts_desc, dense_desc, heatmap = fe.run(gray)

        # ---- metrics ----
        kp = pts[0]
        n_kp = kp.shape[1]

        if n_kp > 0:
            kps_xy = kp[:2].T  # (N, 2)
            entropy, coverage = keypoint_entropy_and_coverage(
                kps_xy,
                H=SP_SIZE[0],
                W=SP_SIZE[1],
                grid=(4, 4)
            )
        else:
            entropy, coverage = 0.0, 0.0

        row[f"{hyp_name}_count"] = n_kp
        row[f"{hyp_name}_entropy"] = entropy
        row[f"{hyp_name}_coverage"] = coverage

    results.append(row)


# =========================
# 5. BUILD PANDAS TABLE
# =========================

df = pd.DataFrame(results)
df = df.set_index("image")

print("\nKeypoint statistics table:")
print(df)


# =========================
# 6. MEAN & STD
# =========================

metric_cols = [
    c for c in df.columns
    if c.endswith(("_count", "_entropy", "_coverage"))
]

stats = pd.DataFrame({
    "mean": df[metric_cols].mean(),
    "std": df[metric_cols].std()
})

print("\nStatistics (per configuration & metric):")
print(stats)

/home/boat/miniconda3/envs/proxyopt/lib/python3.12/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))

24 24
24 24
Found 102 DNG files

Processing RAW images:   0%|                  | 0/102 [00:00<?, ?it/s]

Executing awb... Done. Elapsed 0.019s
Executing cfa... Done. Elapsed 0.111s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.007s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.150s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.731s
Executing awb... Done. Elapsed 0.019s
Executing cfa... Done. Elapsed 0.113s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.038s
Executing csc... Done. Elapsed 0.134s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.858s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.090s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.006s
Executing csc... Done. Elapsed 0.079s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.019s

Processing RAW images:   1%|          | 1/102 [00:02<04:39,  2.77s/it]

Pipeline elapsed 0.703s
Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.080s
Executing eeh... Done. Elapsed 0.145s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.722s
Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.100s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.752s
Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.007s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.731s

Processing RAW images:   2%|▏         | 2/102 [00:05<04:16,  2.57s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.108s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.004s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.728s
Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.111s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.761s
Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.109s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.768s

Processing RAW images:   3%|▎         | 3/102 [00:07<04:09,  2.52s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.160s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.761s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.105s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.146s
Executing hsc... Done. Elapsed 0.060s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.757s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.006s
Executing csc... Done. Elapsed 0.079s
Executing eeh... Done. Elapsed 0.161s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.714s

Processing RAW images:   4%|▍         | 4/102 [00:10<04:01,  2.47s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.113s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.166s
Executing hsc... Done. Elapsed 0.169s
Executing bcc... Done. Elapsed 0.161s
Pipeline elapsed 1.102s
Executing awb... Done. Elapsed 0.086s
Executing cfa... Done. Elapsed 0.512s
Executing ccm... Done. Elapsed 0.390s
Executing gac... Done. Elapsed 0.098s
Executing bnfcv... Done. Elapsed 0.047s
Executing csc... Done. Elapsed 0.355s
Executing eeh... Done. Elapsed 0.717s
Executing hsc... Done. Elapsed 0.222s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 2.621s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.135s
Executing ccm... Done. Elapsed 0.127s
Executing gac... Done. Elapsed 0.057s
Executing bnfcv... Done. Elapsed 0.008s
Executing csc... Done. Elapsed 0.105s
Executing eeh... Done. Elapsed 0.164s
Executing hsc... Done. Elapsed 0.069s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.805s

Processing RAW images:   5%|▍         | 5/102 [00:14<05:24,  3.35s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.114s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.869s
Executing awb... Done. Elapsed 0.017s
Executing cfa... Done. Elapsed 0.112s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.133s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.828s
Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.108s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.129s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.809s

Processing RAW images:   6%|▌         | 6/102 [00:17<05:01,  3.14s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.108s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.724s
Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.089s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.731s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.089s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.006s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.724s

Processing RAW images:   7%|▋         | 7/102 [00:20<04:35,  2.90s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.032s
Executing csc... Done. Elapsed 0.130s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.844s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.099s
Executing ccm... Done. Elapsed 0.105s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.042s
Executing csc... Done. Elapsed 0.130s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.027s
Pipeline elapsed 0.826s
Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.024s
Executing csc... Done. Elapsed 0.124s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.790s

Processing RAW images:   8%|▊         | 8/102 [00:22<04:26,  2.83s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.733s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.042s
Executing csc... Done. Elapsed 0.125s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.823s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.006s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.720s

Processing RAW images:   9%|▉         | 9/102 [00:25<04:13,  2.72s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.126s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.771s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.099s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.136s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.824s
Executing awb... Done. Elapsed 0.016s
Executing cfa... Done. Elapsed 0.508s
Executing ccm... Done. Elapsed 0.332s
Executing gac... Done. Elapsed 0.124s
Executing bnfcv... Done. Elapsed 0.024s
Executing csc... Done. Elapsed 0.299s
Executing eeh... Done. Elapsed 0.968s
Executing hsc... Done. Elapsed 0.234s
Executing bcc... Done. Elapsed 0.069s

Processing RAW images:  10%|▉        | 10/102 [00:30<05:09,  3.36s/it]

Pipeline elapsed 2.888s
Executing awb... Done. Elapsed 0.072s
Executing cfa... Done. Elapsed 0.133s
Executing ccm... Done. Elapsed 0.155s
Executing gac... Done. Elapsed 0.063s
Executing bnfcv... Done. Elapsed 0.022s
Executing csc... Done. Elapsed 0.125s
Executing eeh... Done. Elapsed 0.214s
Executing hsc... Done. Elapsed 0.083s
Executing bcc... Done. Elapsed 0.034s
Pipeline elapsed 1.010s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.042s
Executing csc... Done. Elapsed 0.120s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.822s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.110s
Executing ccm... Done. Elapsed 0.184s
Executing gac... Done. Elapsed 0.066s
Executing bnfcv... Done. Elapsed 0.023s
Executing csc... Done. Elapsed 0.106s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.844s

Processing RAW images:  11%|▉        | 11/102 [00:32<04:53,  3.22s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.741s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.041s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.767s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.007s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.792s

Processing RAW images:  12%|█        | 12/102 [00:35<04:30,  3.01s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.722s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.100s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.755s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.007s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.017s
Pipeline elapsed 0.721s

Processing RAW images:  13%|█▏       | 13/102 [00:37<04:11,  2.83s/it]

Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.022s
Executing csc... Done. Elapsed 0.136s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.808s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.041s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.754s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.023s
Executing csc... Done. Elapsed 0.134s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.061s
Executing bcc... Done. Elapsed 0.017s
Pipeline elapsed 0.800s

Processing RAW images:  14%|█▏       | 14/102 [00:40<04:02,  2.75s/it]

Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.133s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.805s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.042s
Executing csc... Done. Elapsed 0.127s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.815s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.007s
Executing csc... Done. Elapsed 0.133s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.772s

Processing RAW images:  15%|█▎       | 15/102 [00:43<03:55,  2.71s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.133s
Executing eeh... Done. Elapsed 0.149s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.780s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.096s
Executing ccm... Done. Elapsed 0.105s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.097s
Executing eeh... Done. Elapsed 0.150s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.017s
Pipeline elapsed 0.722s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.100s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.007s
Executing csc... Done. Elapsed 0.127s
Executing eeh... Done. Elapsed 0.149s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.768s

Processing RAW images:  16%|█▍       | 16/102 [00:45<03:47,  2.64s/it]

Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.099s
Executing ccm... Done. Elapsed 0.103s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.023s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.165s
Executing hsc... Done. Elapsed 0.083s
Executing bcc... Done. Elapsed 0.176s
Pipeline elapsed 1.054s
Executing awb... Done. Elapsed 0.134s
Executing cfa... Done. Elapsed 0.574s
Executing ccm... Done. Elapsed 0.370s
Executing gac... Done. Elapsed 0.124s
Executing bnfcv... Done. Elapsed 0.079s
Executing csc... Done. Elapsed 0.360s
Executing eeh... Done. Elapsed 0.896s
Executing hsc... Done. Elapsed 0.070s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 2.807s
Executing awb... Done. Elapsed 0.016s
Executing cfa... Done. Elapsed 0.118s
Executing ccm... Done. Elapsed 0.132s
Executing gac... Done. Elapsed 0.064s
Executing bnfcv... Done. Elapsed 0.021s
Executing csc... Done. Elapsed 0.107s
Executing eeh... Done. Elapsed 0.166s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.817s

Processing RAW images:  17%|█▌       | 17/102 [00:50<04:44,  3.35s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.116s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.130s
Executing eeh... Done. Elapsed 0.161s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.799s
Executing awb... Done. Elapsed 0.018s
Executing cfa... Done. Elapsed 0.115s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.164s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.781s
Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.109s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.748s

Processing RAW images:  18%|█▌       | 18/102 [00:53<04:23,  3.13s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.762s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.144s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.744s
Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.092s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.007s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.148s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.727s

Processing RAW images:  19%|█▋       | 19/102 [00:55<04:02,  2.92s/it]

Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.021s
Executing csc... Done. Elapsed 0.137s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.027s
Pipeline elapsed 0.850s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.112s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.043s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.865s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.111s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.025s
Executing csc... Done. Elapsed 0.133s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.830s

Processing RAW images:  20%|█▊       | 20/102 [00:58<03:55,  2.88s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.114s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.005s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.733s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.757s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.089s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.007s
Executing csc... Done. Elapsed 0.078s
Executing eeh... Done. Elapsed 0.148s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.713s

Processing RAW images:  21%|█▊       | 21/102 [01:00<03:42,  2.74s/it]

Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.108s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.761s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.088s
Executing gac... Done. Elapsed 0.046s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.111s
Executing eeh... Done. Elapsed 0.163s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.752s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.768s

Processing RAW images:  22%|█▉       | 22/102 [01:03<03:33,  2.67s/it]

Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.743s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.751s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.734s

Processing RAW images:  23%|██       | 23/102 [01:05<03:25,  2.61s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.063s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.279s
Executing eeh... Done. Elapsed 0.649s
Executing hsc... Done. Elapsed 0.346s
Executing bcc... Done. Elapsed 0.094s
Pipeline elapsed 1.974s
Executing awb... Done. Elapsed 0.018s
Executing cfa... Done. Elapsed 0.612s
Executing ccm... Done. Elapsed 0.316s
Executing gac... Done. Elapsed 0.129s
Executing bnfcv... Done. Elapsed 0.047s
Executing csc... Done. Elapsed 0.207s
Executing eeh... Done. Elapsed 0.250s
Executing hsc... Done. Elapsed 0.069s
Executing bcc... Done. Elapsed 0.033s
Pipeline elapsed 1.804s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.119s
Executing ccm... Done. Elapsed 0.121s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.804s

Processing RAW images:  24%|██       | 24/102 [01:10<04:18,  3.31s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.159s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.838s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.032s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.758s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.733s

Processing RAW images:  25%|██▏      | 25/102 [01:13<03:57,  3.09s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.738s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.088s
Executing gac... Done. Elapsed 0.046s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.740s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.780s

Processing RAW images:  25%|██▎      | 26/102 [01:15<03:40,  2.91s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.104s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.755s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.032s
Executing csc... Done. Elapsed 0.109s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.766s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.747s

Processing RAW images:  26%|██▍      | 27/102 [01:18<03:28,  2.78s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.753s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.091s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.161s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.749s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.110s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.790s

Processing RAW images:  27%|██▍      | 28/102 [01:20<03:19,  2.70s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.736s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.746s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.732s

Processing RAW images:  28%|██▌      | 29/102 [01:23<03:11,  2.62s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.746s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.090s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.179s
Executing hsc... Done. Elapsed 0.296s
Executing bcc... Done. Elapsed 0.057s
Pipeline elapsed 1.197s
Executing awb... Done. Elapsed 0.023s
Executing cfa... Done. Elapsed 0.566s
Executing ccm... Done. Elapsed 0.356s
Executing gac... Done. Elapsed 0.084s
Executing bnfcv... Done. Elapsed 0.035s
Executing csc... Done. Elapsed 0.339s
Executing eeh... Done. Elapsed 0.823s
Executing hsc... Done. Elapsed 0.122s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 2.556s

Processing RAW images:  29%|██▋      | 30/102 [01:28<03:57,  3.29s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.148s
Executing ccm... Done. Elapsed 0.122s
Executing gac... Done. Elapsed 0.059s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.141s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.885s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.109s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.105s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.837s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.109s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.137s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.823s

Processing RAW images:  30%|██▋      | 31/102 [01:30<03:42,  3.14s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.113s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.136s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.815s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.090s
Executing gac... Done. Elapsed 0.046s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.107s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.775s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.775s

Processing RAW images:  31%|██▊      | 32/102 [01:33<03:27,  2.97s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.105s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.730s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.032s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.750s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.114s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.016s
Pipeline elapsed 0.736s

Processing RAW images:  32%|██▉      | 33/102 [01:35<03:13,  2.81s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.111s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.739s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.087s
Executing gac... Done. Elapsed 0.045s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.017s
Pipeline elapsed 0.720s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.108s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.770s

Processing RAW images:  33%|███      | 34/102 [01:38<03:03,  2.70s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.729s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.108s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.758s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.731s

Processing RAW images:  34%|███      | 35/102 [01:40<02:55,  2.62s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.016s
Pipeline elapsed 0.730s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.263s
Executing gac... Done. Elapsed 0.144s
Executing bnfcv... Done. Elapsed 0.037s
Executing csc... Done. Elapsed 0.177s
Executing eeh... Done. Elapsed 0.894s
Executing hsc... Done. Elapsed 0.270s
Executing bcc... Done. Elapsed 0.099s
Pipeline elapsed 2.357s
Executing awb... Done. Elapsed 0.053s
Executing cfa... Done. Elapsed 0.524s
Executing ccm... Done. Elapsed 0.253s
Executing gac... Done. Elapsed 0.054s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.152s
Executing eeh... Done. Elapsed 0.177s
Executing hsc... Done. Elapsed 0.091s
Executing bcc... Done. Elapsed 0.041s
Pipeline elapsed 1.508s

Processing RAW images:  35%|███▏     | 36/102 [01:45<03:38,  3.31s/it]

Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.114s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.163s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.762s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.108s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.281s
Executing hsc... Done. Elapsed 0.077s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.900s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.115s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.017s
Pipeline elapsed 0.780s

Processing RAW images:  36%|███▎     | 37/102 [01:48<03:22,  3.12s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.108s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.160s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.755s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.110s
Executing ccm... Done. Elapsed 0.089s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.734s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.105s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.162s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.772s

Processing RAW images:  37%|███▎     | 38/102 [01:50<03:07,  2.93s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.134s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.807s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.032s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.757s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.061s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.731s

Processing RAW images:  38%|███▍     | 39/102 [01:53<02:56,  2.80s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.734s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.088s
Executing gac... Done. Elapsed 0.046s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.725s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.108s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.770s

Processing RAW images:  39%|███▌     | 40/102 [01:55<02:47,  2.70s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.733s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.148s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.017s
Pipeline elapsed 0.738s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.743s

Processing RAW images:  40%|███▌     | 41/102 [01:58<02:39,  2.62s/it]

Executing awb... Done. Elapsed 0.090s
Executing cfa... Done. Elapsed 0.516s
Executing ccm... Done. Elapsed 0.256s
Executing gac... Done. Elapsed 0.255s
Executing bnfcv... Done. Elapsed 0.023s
Executing csc... Done. Elapsed 0.193s
Executing eeh... Done. Elapsed 0.903s
Executing hsc... Done. Elapsed 0.301s
Executing bcc... Done. Elapsed 0.116s
Pipeline elapsed 2.905s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.168s
Executing ccm... Done. Elapsed 0.103s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.036s
Executing csc... Done. Elapsed 0.120s
Executing eeh... Done. Elapsed 0.221s
Executing hsc... Done. Elapsed 0.080s
Executing bcc... Done. Elapsed 0.029s
Pipeline elapsed 0.926s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.168s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.792s

Processing RAW images:  41%|███▋     | 42/102 [02:03<03:19,  3.33s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.166s
Executing gac... Done. Elapsed 0.063s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.109s
Executing eeh... Done. Elapsed 0.161s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.829s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.746s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.150s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.736s

Processing RAW images:  42%|███▊     | 43/102 [02:05<03:02,  3.09s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.744s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.087s
Executing gac... Done. Elapsed 0.044s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.132s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.786s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.137s
Executing eeh... Done. Elapsed 0.150s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.843s

Processing RAW images:  43%|███▉     | 44/102 [02:08<02:50,  2.94s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.738s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.743s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.735s

Processing RAW images:  44%|███▉     | 45/102 [02:10<02:38,  2.79s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.742s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.087s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.017s
Pipeline elapsed 0.727s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.774s

Processing RAW images:  45%|████     | 46/102 [02:13<02:30,  2.69s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.100s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.132s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.017s
Pipeline elapsed 0.790s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.748s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.025s

Processing RAW images:  46%|████▏    | 47/102 [02:15<02:28,  2.71s/it]

Pipeline elapsed 0.930s
Executing awb... Done. Elapsed 0.051s
Executing cfa... Done. Elapsed 0.528s
Executing ccm... Done. Elapsed 0.333s
Executing gac... Done. Elapsed 0.109s
Executing bnfcv... Done. Elapsed 0.033s
Executing csc... Done. Elapsed 0.259s
Executing eeh... Done. Elapsed 0.689s
Executing hsc... Done. Elapsed 0.177s
Executing bcc... Done. Elapsed 0.151s
Pipeline elapsed 2.599s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.173s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.028s
Executing csc... Done. Elapsed 0.121s
Executing eeh... Done. Elapsed 0.226s
Executing hsc... Done. Elapsed 0.081s
Executing bcc... Done. Elapsed 0.028s
Pipeline elapsed 0.939s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.105s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.166s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.779s

Processing RAW images:  47%|████▏    | 48/102 [02:20<02:57,  3.29s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.173s
Executing gac... Done. Elapsed 0.058s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.143s
Executing eeh... Done. Elapsed 0.163s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.899s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.105s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.744s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.105s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.740s

Processing RAW images:  48%|████▎    | 49/102 [02:23<02:43,  3.08s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.749s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.088s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.027s
Pipeline elapsed 0.734s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.165s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.777s

Processing RAW images:  49%|████▍    | 50/102 [02:25<02:30,  2.90s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.119s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.783s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.110s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.756s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.734s

Processing RAW images:  50%|████▌    | 51/102 [02:28<02:21,  2.78s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.733s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.087s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.132s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.786s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.765s

Processing RAW images:  51%|████▌    | 52/102 [02:30<02:14,  2.69s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.735s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.129s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.806s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.061s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.730s

Processing RAW images:  52%|████▋    | 53/102 [02:33<02:08,  2.63s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.122s
Executing gac... Done. Elapsed 0.197s
Executing bnfcv... Done. Elapsed 0.047s
Executing csc... Done. Elapsed 0.206s
Executing eeh... Done. Elapsed 0.787s
Executing hsc... Done. Elapsed 0.216s
Executing bcc... Done. Elapsed 0.059s
Pipeline elapsed 2.065s
Executing awb... Done. Elapsed 0.066s
Executing cfa... Done. Elapsed 0.530s
Executing ccm... Done. Elapsed 0.307s
Executing gac... Done. Elapsed 0.057s
Executing bnfcv... Done. Elapsed 0.063s
Executing csc... Done. Elapsed 0.176s
Executing eeh... Done. Elapsed 0.264s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 1.683s
Executing awb... Done. Elapsed 0.020s
Executing cfa... Done. Elapsed 0.134s
Executing ccm... Done. Elapsed 0.122s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.828s

Processing RAW images:  53%|████▊    | 54/102 [02:38<02:38,  3.30s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.054s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.164s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.853s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.032s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.757s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.023s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.742s

Processing RAW images:  54%|████▊    | 55/102 [02:40<02:24,  3.08s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.748s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.088s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.161s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.745s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.160s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.788s

Processing RAW images:  55%|████▉    | 56/102 [02:43<02:13,  2.91s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.748s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.752s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.742s

Processing RAW images:  56%|█████    | 57/102 [02:45<02:04,  2.77s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.747s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.087s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.731s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.111s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.054s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.161s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.027s
Pipeline elapsed 0.785s

Processing RAW images:  57%|█████    | 58/102 [02:48<01:58,  2.69s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.099s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.730s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.745s
Executing awb... Done. Elapsed 0.016s
Executing cfa... Done. Elapsed 0.523s
Executing ccm... Done. Elapsed 0.329s
Executing gac... Done. Elapsed 0.230s
Executing bnfcv... Done. Elapsed 0.037s
Executing csc... Done. Elapsed 0.247s
Executing eeh... Done. Elapsed 0.925s
Executing hsc... Done. Elapsed 0.197s
Executing bcc... Done. Elapsed 0.066s

Processing RAW images:  58%|█████▏   | 59/102 [02:52<02:21,  3.28s/it]

Pipeline elapsed 2.860s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.163s
Executing ccm... Done. Elapsed 0.143s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.130s
Executing eeh... Done. Elapsed 0.237s
Executing hsc... Done. Elapsed 0.071s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.955s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.089s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.740s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.184s
Executing gac... Done. Elapsed 0.071s
Executing bnfcv... Done. Elapsed 0.021s
Executing csc... Done. Elapsed 0.105s
Executing eeh... Done. Elapsed 0.163s
Executing hsc... Done. Elapsed 0.070s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.887s

Processing RAW images:  59%|█████▎   | 60/102 [02:55<02:12,  3.15s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.161s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.741s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.032s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.741s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.740s

Processing RAW images:  60%|█████▍   | 61/102 [02:58<02:00,  2.94s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.015s
Executing csc... Done. Elapsed 0.134s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.805s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.089s
Executing gac... Done. Elapsed 0.045s
Executing bnfcv... Done. Elapsed 0.032s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.727s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.764s

Processing RAW images:  61%|█████▍   | 62/102 [03:00<01:52,  2.81s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.730s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.750s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.134s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.061s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.805s

Processing RAW images:  62%|█████▌   | 63/102 [03:03<01:46,  2.72s/it]

Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.069s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.822s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.091s
Executing gac... Done. Elapsed 0.046s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.731s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.777s

Processing RAW images:  63%|█████▋   | 64/102 [03:05<01:41,  2.67s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.210s
Executing ccm... Done. Elapsed 0.335s
Executing gac... Done. Elapsed 0.087s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.293s
Executing eeh... Done. Elapsed 0.831s
Executing hsc... Done. Elapsed 0.235s
Executing bcc... Done. Elapsed 0.133s
Pipeline elapsed 2.454s
Executing awb... Done. Elapsed 0.029s
Executing cfa... Done. Elapsed 0.608s
Executing ccm... Done. Elapsed 0.143s
Executing gac... Done. Elapsed 0.096s
Executing bnfcv... Done. Elapsed 0.028s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.256s
Executing hsc... Done. Elapsed 0.089s
Executing bcc... Done. Elapsed 0.028s
Pipeline elapsed 1.491s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.114s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.748s

Processing RAW images:  64%|█████▋   | 65/102 [03:10<02:04,  3.36s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.109s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.184s
Executing eeh... Done. Elapsed 0.186s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.893s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.092s
Executing gac... Done. Elapsed 0.044s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.130s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.788s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.129s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.825s

Processing RAW images:  65%|█████▊   | 66/102 [03:13<01:54,  3.17s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.149s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.726s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.032s
Executing csc... Done. Elapsed 0.112s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.758s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.732s

Processing RAW images:  66%|█████▉   | 67/102 [03:15<01:43,  2.95s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.133s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.820s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.086s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.727s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.771s

Processing RAW images:  67%|██████   | 68/102 [03:18<01:36,  2.83s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.737s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.754s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.732s

Processing RAW images:  68%|██████   | 69/102 [03:20<01:29,  2.71s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.134s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.810s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.110s
Executing ccm... Done. Elapsed 0.090s
Executing gac... Done. Elapsed 0.045s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.133s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.809s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.114s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.848s

Processing RAW images:  69%|██████▏  | 70/102 [03:23<01:26,  2.71s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.105s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.735s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.760s
Executing awb... Done. Elapsed 0.107s
Executing cfa... Done. Elapsed 0.522s
Executing ccm... Done. Elapsed 0.318s
Executing gac... Done. Elapsed 0.241s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.191s
Executing eeh... Done. Elapsed 0.889s
Executing hsc... Done. Elapsed 0.209s
Executing bcc... Done. Elapsed 0.062s

Processing RAW images:  70%|██████▎  | 71/102 [03:28<01:42,  3.29s/it]

Pipeline elapsed 2.860s
Executing awb... Done. Elapsed 0.071s
Executing cfa... Done. Elapsed 0.137s
Executing ccm... Done. Elapsed 0.158s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.150s
Executing eeh... Done. Elapsed 0.227s
Executing hsc... Done. Elapsed 0.072s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 1.045s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.090s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.032s
Executing csc... Done. Elapsed 0.131s
Executing eeh... Done. Elapsed 0.161s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.801s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.183s
Executing gac... Done. Elapsed 0.061s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.936s

Processing RAW images:  71%|██████▎  | 72/102 [03:31<01:36,  3.21s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.748s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.758s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.782s

Processing RAW images:  72%|██████▍  | 73/102 [03:33<01:27,  3.01s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.017s
Pipeline elapsed 0.783s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.093s
Executing gac... Done. Elapsed 0.045s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.160s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.737s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.134s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.828s

Processing RAW images:  73%|██████▌  | 74/102 [03:36<01:20,  2.88s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.729s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.741s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.729s

Processing RAW images:  74%|██████▌  | 75/102 [03:38<01:13,  2.74s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.804s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.088s
Executing gac... Done. Elapsed 0.045s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.134s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.791s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.133s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.830s

Processing RAW images:  75%|██████▋  | 76/102 [03:41<01:10,  2.71s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.729s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.752s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.126s
Executing gac... Done. Elapsed 0.237s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.194s
Executing eeh... Done. Elapsed 0.864s
Executing hsc... Done. Elapsed 0.211s
Executing bcc... Done. Elapsed 0.154s
Pipeline elapsed 2.182s

Processing RAW images:  75%|██████▊  | 77/102 [03:45<01:18,  3.13s/it]

Executing awb... Done. Elapsed 0.060s
Executing cfa... Done. Elapsed 0.463s
Executing ccm... Done. Elapsed 0.247s
Executing gac... Done. Elapsed 0.066s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.166s
Executing eeh... Done. Elapsed 0.205s
Executing hsc... Done. Elapsed 0.087s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 1.475s
Executing awb... Done. Elapsed 0.020s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.094s
Executing gac... Done. Elapsed 0.046s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.127s
Executing eeh... Done. Elapsed 0.166s
Executing hsc... Done. Elapsed 0.070s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.809s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.178s
Executing eeh... Done. Elapsed 0.211s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.944s

Processing RAW images:  76%|██████▉  | 78/102 [03:48<01:17,  3.23s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.741s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.744s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.738s

Processing RAW images:  77%|██████▉  | 79/102 [03:51<01:08,  3.00s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.136s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.819s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.090s
Executing gac... Done. Elapsed 0.045s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.734s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.841s

Processing RAW images:  78%|███████  | 80/102 [03:53<01:03,  2.89s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.100s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.069s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.730s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.100s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.111s
Executing eeh... Done. Elapsed 0.149s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.749s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.133s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.793s

Processing RAW images:  79%|███████▏ | 81/102 [03:56<00:58,  2.77s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.740s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.087s
Executing gac... Done. Elapsed 0.046s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.107s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.731s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.764s

Processing RAW images:  80%|███████▏ | 82/102 [03:58<00:53,  2.68s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.100s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.028s
Pipeline elapsed 0.738s
Executing awb... Done. Elapsed 0.019s
Executing cfa... Done. Elapsed 0.312s
Executing ccm... Done. Elapsed 0.255s
Executing gac... Done. Elapsed 0.212s
Executing bnfcv... Done. Elapsed 0.052s
Executing csc... Done. Elapsed 0.223s
Executing eeh... Done. Elapsed 0.814s
Executing hsc... Done. Elapsed 0.204s
Executing bcc... Done. Elapsed 0.169s
Pipeline elapsed 2.513s
Executing awb... Done. Elapsed 0.089s
Executing cfa... Done. Elapsed 0.375s
Executing ccm... Done. Elapsed 0.142s
Executing gac... Done. Elapsed 0.088s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.104s
Executing eeh... Done. Elapsed 0.239s
Executing hsc... Done. Elapsed 0.075s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 1.270s

Processing RAW images:  81%|███████▎ | 83/102 [04:03<01:03,  3.34s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.028s
Pipeline elapsed 0.758s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.087s
Executing gac... Done. Elapsed 0.045s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.104s
Executing eeh... Done. Elapsed 0.278s
Executing hsc... Done. Elapsed 0.072s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.860s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.163s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.785s

Processing RAW images:  82%|███████▍ | 84/102 [04:06<00:56,  3.12s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.100s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.731s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.754s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.747s

Processing RAW images:  83%|███████▌ | 85/102 [04:08<00:49,  2.92s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.160s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.752s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.088s
Executing gac... Done. Elapsed 0.045s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.733s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.766s

Processing RAW images:  84%|███████▌ | 86/102 [04:11<00:44,  2.79s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.733s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.149s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.745s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.737s

Processing RAW images:  85%|███████▋ | 87/102 [04:13<00:40,  2.68s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.747s
Executing awb... Done. Elapsed 0.018s
Executing cfa... Done. Elapsed 0.437s
Executing ccm... Done. Elapsed 0.363s
Executing gac... Done. Elapsed 0.062s
Executing bnfcv... Done. Elapsed 0.059s
Executing csc... Done. Elapsed 0.313s
Executing eeh... Done. Elapsed 0.743s
Executing hsc... Done. Elapsed 0.327s
Executing bcc... Done. Elapsed 0.080s
Pipeline elapsed 2.726s
Executing awb... Done. Elapsed 0.020s
Executing cfa... Done. Elapsed 0.286s
Executing ccm... Done. Elapsed 0.178s
Executing gac... Done. Elapsed 0.055s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.117s
Executing eeh... Done. Elapsed 0.266s
Executing hsc... Done. Elapsed 0.079s
Executing bcc... Done. Elapsed 0.030s
Pipeline elapsed 1.181s

Processing RAW images:  86%|███████▊ | 88/102 [04:18<00:47,  3.37s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.160s
Executing hsc... Done. Elapsed 0.069s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.754s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.053s
Executing csc... Done. Elapsed 0.125s
Executing eeh... Done. Elapsed 0.170s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.028s
Pipeline elapsed 0.825s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.153s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.740s

Processing RAW images:  87%|███████▊ | 89/102 [04:21<00:40,  3.12s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.053s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.159s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.756s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.090s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.130s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.071s
Executing bcc... Done. Elapsed 0.029s
Pipeline elapsed 0.822s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.160s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.786s

Processing RAW images:  88%|███████▉ | 90/102 [04:23<00:35,  2.96s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.160s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.746s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.136s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.821s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.130s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.796s

Processing RAW images:  89%|████████ | 91/102 [04:26<00:31,  2.85s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.112s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.142s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.829s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.089s
Executing gac... Done. Elapsed 0.044s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.151s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.024s
Pipeline elapsed 0.790s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.131s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.821s

Processing RAW images:  90%|████████ | 92/102 [04:29<00:27,  2.79s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.099s
Executing ccm... Done. Elapsed 0.107s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.134s
Executing eeh... Done. Elapsed 0.150s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.789s
Executing awb... Done. Elapsed 0.017s
Executing cfa... Done. Elapsed 0.411s
Executing ccm... Done. Elapsed 0.380s
Executing gac... Done. Elapsed 0.072s
Executing bnfcv... Done. Elapsed 0.051s
Executing csc... Done. Elapsed 0.313s
Executing eeh... Done. Elapsed 0.782s
Executing hsc... Done. Elapsed 0.321s
Executing bcc... Done. Elapsed 0.088s
Pipeline elapsed 2.744s
Executing awb... Done. Elapsed 0.043s
Executing cfa... Done. Elapsed 0.272s
Executing ccm... Done. Elapsed 0.176s
Executing gac... Done. Elapsed 0.054s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.116s
Executing eeh... Done. Elapsed 0.261s
Executing hsc... Done. Elapsed 0.086s
Executing bcc... Done. Elapsed 0.023s

Processing RAW images:  91%|████████▏| 93/102 [04:34<00:31,  3.45s/it]

Pipeline elapsed 1.163s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.162s
Executing hsc... Done. Elapsed 0.070s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.765s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.093s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.187s
Executing eeh... Done. Elapsed 0.173s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.848s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.108s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.786s

Processing RAW images:  92%|████████▎| 94/102 [04:36<00:25,  3.21s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.749s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.103s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.759s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.111s
Executing ccm... Done. Elapsed 0.115s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.750s

Processing RAW images:  93%|████████▍| 95/102 [04:39<00:20,  2.99s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.107s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.136s
Executing eeh... Done. Elapsed 0.156s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.827s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.103s
Executing ccm... Done. Elapsed 0.087s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.098s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.026s
Pipeline elapsed 0.730s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.109s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.025s
Pipeline elapsed 0.773s

Processing RAW images:  94%|████████▍| 96/102 [04:41<00:17,  2.86s/it]

Executing awb... Done. Elapsed 0.011s
Executing cfa... Done. Elapsed 0.100s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.050s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.732s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.101s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.048s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.780s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.108s
Executing ccm... Done. Elapsed 0.106s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.020s
Executing csc... Done. Elapsed 0.135s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.801s

Processing RAW images:  95%|████████▌| 97/102 [04:44<00:13,  2.76s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.158s
Executing hsc... Done. Elapsed 0.070s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.754s
Executing awb... Done. Elapsed 0.016s
Executing cfa... Done. Elapsed 0.108s
Executing ccm... Done. Elapsed 0.091s
Executing gac... Done. Elapsed 0.047s
Executing bnfcv... Done. Elapsed 0.029s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.160s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.747s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.102s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.064s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.293s
Executing eeh... Done. Elapsed 0.892s
Executing hsc... Done. Elapsed 0.231s
Executing bcc... Done. Elapsed 0.091s

Processing RAW images:  96%|████████▋| 98/102 [04:48<00:12,  3.12s/it]

Pipeline elapsed 2.146s
Executing awb... Done. Elapsed 0.125s
Executing cfa... Done. Elapsed 0.496s
Executing ccm... Done. Elapsed 0.319s
Executing gac... Done. Elapsed 0.127s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.108s
Executing eeh... Done. Elapsed 0.251s
Executing hsc... Done. Elapsed 0.080s
Executing bcc... Done. Elapsed 0.049s
Pipeline elapsed 1.712s
Executing awb... Done. Elapsed 0.018s
Executing cfa... Done. Elapsed 0.116s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.166s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.027s
Pipeline elapsed 0.795s
Executing awb... Done. Elapsed 0.015s
Executing cfa... Done. Elapsed 0.106s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.019s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.245s
Executing hsc... Done. Elapsed 0.078s
Executing bcc... Done. Elapsed 0.023s

Processing RAW images:  97%|████████▋| 99/102 [04:51<00:09,  3.27s/it]

Pipeline elapsed 0.860s
Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.109s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.161s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.020s
Pipeline elapsed 0.758s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.091s
Executing gac... Done. Elapsed 0.046s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.067s
Executing bcc... Done. Elapsed 0.023s
Pipeline elapsed 0.734s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.109s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.154s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.772s

Processing RAW images:  98%|███████▊| 100/102 [04:54<00:06,  3.04s/it]

Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.016s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.068s
Executing bcc... Done. Elapsed 0.019s
Pipeline elapsed 0.744s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.104s
Executing ccm... Done. Elapsed 0.108s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.031s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.150s
Executing hsc... Done. Elapsed 0.064s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.746s
Executing awb... Done. Elapsed 0.012s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.110s
Executing gac... Done. Elapsed 0.049s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.101s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.063s
Executing bcc... Done. Elapsed 0.018s
Pipeline elapsed 0.732s

Processing RAW images:  99%|███████▉| 101/102 [04:56<00:02,  2.86s/it]

Executing awb... Done. Elapsed 0.013s
Executing cfa... Done. Elapsed 0.114s
Executing ccm... Done. Elapsed 0.113s
Executing gac... Done. Elapsed 0.052s
Executing bnfcv... Done. Elapsed 0.017s
Executing csc... Done. Elapsed 0.100s
Executing eeh... Done. Elapsed 0.155s
Executing hsc... Done. Elapsed 0.066s
Executing bcc... Done. Elapsed 0.021s
Pipeline elapsed 0.756s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.088s
Executing gac... Done. Elapsed 0.046s
Executing bnfcv... Done. Elapsed 0.030s
Executing csc... Done. Elapsed 0.099s
Executing eeh... Done. Elapsed 0.157s
Executing hsc... Done. Elapsed 0.065s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.731s
Executing awb... Done. Elapsed 0.014s
Executing cfa... Done. Elapsed 0.105s
Executing ccm... Done. Elapsed 0.111s
Executing gac... Done. Elapsed 0.051s
Executing bnfcv... Done. Elapsed 0.018s
Executing csc... Done. Elapsed 0.102s
Executing eeh... Done. Elapsed 0.152s
Executing hsc... Done. Elapsed 0.062s
Executing bcc... Done. Elapsed 0.022s
Pipeline elapsed 0.768s

Processing RAW images: 100%|████████| 102/102 [04:59<00:00,  2.93s/it]

Keypoint statistics table:
                    count  original_count  original_entropy  \
image
sl_carforcat/1.dng      0             358          0.948620
sl_carforcat/2.dng      1             355          0.952793
sl_carforcat/3.dng      2             354          0.953003
sl_carforcat/4.dng      3             368          0.957454
sl_carforcat/5.dng      4             372          0.958199
...                   ...             ...               ...
sl_thaicult/2.dng      97             418          0.989477
sl_thaicult/3.dng      98             391          0.984611
sl_thaicult/4.dng      99             395          0.985977
sl_thaicult/5.dng     100             422          0.983656
sl_thaicult/6.dng     101             443          0.982865

                    original_coverage  checkpoint_120000.pkl_count  \
image
sl_carforcat/1.dng                1.0                          355
sl_carforcat/2.dng                1.0                          353
sl_carforcat/3.dng                1.0                          353
sl_carforcat/4.dng                1.0                          362
sl_carforcat/5.dng                1.0                          367
...                               ...                          ...
sl_thaicult/2.dng                 1.0                          410
sl_thaicult/3.dng                 1.0                          399
sl_thaicult/4.dng                 1.0                          400
sl_thaicult/5.dng                 1.0                          412
sl_thaicult/6.dng                 1.0                          430

                    checkpoint_120000.pkl_entropy  \
image
sl_carforcat/1.dng                       0.948052
sl_carforcat/2.dng                       0.954317
sl_carforcat/3.dng                       0.948623
sl_carforcat/4.dng                       0.956753
sl_carforcat/5.dng                       0.957559
...                                           ...
sl_thaicult/2.dng                        0.986852
sl_thaicult/3.dng                        0.982435
sl_thaicult/4.dng                        0.985752
sl_thaicult/5.dng                        0.983435
sl_thaicult/6.dng                        0.983041

                    checkpoint_120000.pkl_coverage  \
image
sl_carforcat/1.dng                             1.0
sl_carforcat/2.dng                             1.0
sl_carforcat/3.dng                             1.0
sl_carforcat/4.dng                             1.0
sl_carforcat/5.dng                             1.0
...                                            ...
sl_thaicult/2.dng                              1.0
sl_thaicult/3.dng                              1.0
sl_thaicult/4.dng                              1.0
sl_thaicult/5.dng                              1.0
sl_thaicult/6.dng                              1.0

                    checkpoint_78500.pkl_count  checkpoint_78500.pkl_entropy  \
image
sl_carforcat/1.dng                         355                      0.948033
sl_carforcat/2.dng                         352                      0.953097
sl_carforcat/3.dng                         357                      0.951983
sl_carforcat/4.dng                         362                      0.951894
sl_carforcat/5.dng                         371                      0.958016
...                                        ...                           ...
sl_thaicult/2.dng                          418                      0.989562
sl_thaicult/3.dng                          391                      0.984828
sl_thaicult/4.dng                          398                      0.985620
sl_thaicult/5.dng                          422                      0.983605
sl_thaicult/6.dng                          440                      0.981865

                    checkpoint_78500.pkl_coverage
image
sl_carforcat/1.dng                            1.0
sl_carforcat/2.dng                            1.0
sl_carforcat/3.dng                            1.0
sl_carforcat/4.dng                            1.0
sl_carforcat/5.dng                            1.0
...                                           ...
sl_thaicult/2.dng                             1.0
sl_thaicult/3.dng                             1.0
sl_thaicult/4.dng                             1.0
sl_thaicult/5.dng                             1.0
sl_thaicult/6.dng                             1.0

[102 rows x 10 columns]

Statistics (per configuration & metric):
                                      mean        std
original_count                  391.882353  62.859626
original_entropy                  0.970810   0.016278
original_coverage                 1.000000   0.000000
checkpoint_120000.pkl_count     388.558824  62.474323
checkpoint_120000.pkl_entropy     0.969111   0.017813
checkpoint_120000.pkl_coverage    0.999387   0.006188
checkpoint_78500.pkl_count      390.225490  62.838297
checkpoint_78500.pkl_entropy      0.970440   0.016237
checkpoint_78500.pkl_coverage     0.999387   0.006188

In [4]:
df

,count,original_count,original_entropy,original_coverage,checkpoint_120000.pkl_count,checkpoint_120000.pkl_entropy,checkpoint_120000.pkl_coverage,checkpoint_78500.pkl_count,checkpoint_78500.pkl_entropy,checkpoint_78500.pkl_coverage
image,,,,,,,,,,
sl_carforcat/1.dng,0,358,0.948620,1.0,355,0.948052,1.0,355,0.948033,1.0
sl_carforcat/2.dng,1,355,0.952793,1.0,353,0.954317,1.0,352,0.953097,1.0
sl_carforcat/3.dng,2,354,0.953003,1.0,353,0.948623,1.0,357,0.951983,1.0
sl_carforcat/4.dng,3,368,0.957454,1.0,362,0.956753,1.0,362,0.951894,1.0
sl_carforcat/5.dng,4,372,0.958199,1.0,367,0.957559,1.0,371,0.958016,1.0
...,...,...,...,...,...,...,...,...,...,...
sl_thaicult/2.dng,97,418,0.989477,1.0,410,0.986852,1.0,418,0.989562,1.0
sl_thaicult/3.dng,98,391,0.984611,1.0,399,0.982435,1.0,391,0.984828,1.0
sl_thaicult/4.dng,99,395,0.985977,1.0,400,0.985752,1.0,398,0.985620,1.0
sl_thaicult/5.dng,100,422,0.983656,1.0,412,0.983435,1.0,422,0.983605,1.0
sl_thaicult/6.dng,101,443,0.982865,1.0,430,0.983041,1.0,440,0.981865,1.0

In [5]:
stats

                                      mean        std
original_count                  391.882353  62.859626
original_entropy                  0.970810   0.016278
original_coverage                 1.000000   0.000000
checkpoint_120000.pkl_count     388.558824  62.474323
checkpoint_120000.pkl_entropy     0.969111   0.017813
checkpoint_120000.pkl_coverage    0.999387   0.006188
checkpoint_78500.pkl_count      390.225490  62.838297
checkpoint_78500.pkl_entropy      0.970440   0.016237
checkpoint_78500.pkl_coverage     0.999387   0.006188